In [1]:
import pandas as pd
import urllib.request
from urllib.request import urlopen
from bs4 import BeautifulSoup
import csv

In [2]:
url = 'https://basketball.realgm.com/ncaa/stats/2021/Averages/Qualified/All/Season/All/points/desc/1/'
page = urlopen(url)
soup = BeautifulSoup(page,'html.parser')
table = soup.find('table')

In [3]:
output_rows = []
for table_row in table.findAll('tr'):
    columns = table_row.findAll('td')
    output_row = []
    for column in columns:
        output_row.append(column.text)
    output_rows.append(output_row)
    
with open('NCAA2021Stats.csv','w') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(output_rows)

In [4]:
columns = ['#','Player','Team','GP','MPG','FGM','FGA','FG%','3PM','3PA','3P%','FTM','FTA','FT%','TOV','PG','ORB','DRB','RPG','AGP','SPG','BPG','PPG']

In [5]:
PPGNCAAstats = pd.read_csv('/Users/nickseah/IEE 577/Team Project/NCAA2021Stats.csv',names = columns, index_col = '#' )

In [6]:
PPGNCAAstats.head()

,Player,Team,GP,MPG,FGM,FGA,FG%,3PM,3PA,3P%,...,FT%,TOV,PG,ORB,DRB,RPG,AGP,SPG,BPG,PPG
#,,,,,,,,,,,,,,,,,,,,,
1,Luka Garza,UI,19,30.5,9.5,16.3,0.583,1.4,3.2,0.450,...,0.719,1.5,2.3,2.9,5.4,8.4,1.7,0.4,1.6,25.5
2,Max Abmas,ORU,16,37.4,7.7,17.0,0.452,3.8,8.9,0.420,...,0.879,1.8,2.4,0.4,3.0,3.4,3.7,1.6,0.2,22.8
3,A.J. Green,UNI,3,36.3,8.7,18.7,0.464,3.7,9.0,0.407,...,0.667,3.7,2.0,1.0,4.7,5.7,2.7,1.3,0.7,22.3
4,Michael Flowers,USA,19,36.8,7.2,15.3,0.471,3.4,8.0,0.421,...,0.796,3.3,2.2,0.4,3.9,4.3,3.7,1.6,0.1,22.3
5,Cam Thomas,LSU,17,31.6,6.7,16.9,0.397,2.2,7.7,0.290,...,0.897,2.2,1.3,0.5,2.2,2.7,1.3,0.9,0.1,22.3

In [7]:
url1 = 'https://basketball.realgm.com/ncaa/stats/2021/Averages/Qualified/All/Season/All/assists/desc/1/'
page1 = urlopen(url1)
soup1 = BeautifulSoup(page1,'html.parser')
table1 = soup1.find('table')

In [8]:
output_rows1 = []
for table_row in table1.findAll('tr'):
    columns1 = table_row.findAll('td')
    output_row1 = []
    for column1 in columns1:
        output_row1.append(column1.text)
    output_rows1.append(output_row1)
    
with open('APGNCAA2021Stats.csv','w') as csvfile1:
    writer1 = csv.writer(csvfile1)
    writer1.writerows(output_rows1)

In [9]:
APGNCAAstats = pd.read_csv('/Users/nickseah/IEE 577/Team Project/APGNCAA2021Stats.csv',names = columns, index_col = '#' )
APGNCAAstats.head()

,Player,Team,GP,MPG,FGM,FGA,FG%,3PM,3PA,3P%,...,FT%,TOV,PG,ORB,DRB,RPG,AGP,SPG,BPG,PPG
#,,,,,,,,,,,,,,,,,,,,,
1,Cam Mack,PVAMU,8,36.0,5.0,12.0,0.417,1.5,5.6,0.267,...,0.742,2.8,2.4,0.9,2.1,3.0,8.5,2.2,0.4,14.4
2,Jalen Moore,OU,23,36.7,5.7,14.0,0.402,1.8,4.8,0.373,...,0.757,4.0,1.6,0.2,3.7,3.9,8.0,1.9,0.0,18.7
3,Colbey Ross,PU,16,36.8,5.2,12.4,0.424,1.6,4.8,0.325,...,0.839,3.8,2.6,0.6,3.4,3.9,7.6,1.4,0.3,16.9
4,Kendric Davis,SMU,15,34.1,6.4,13.6,0.471,1.2,3.7,0.321,...,0.859,2.6,1.5,0.5,3.6,4.1,7.6,1.5,0.1,17.7
5,Sahvir Wheeler,UGA,18,33.9,5.1,12.9,0.392,0.8,3.1,0.273,...,0.676,4.4,2.4,0.7,2.7,3.4,7.4,1.5,0.1,13.6

In [10]:
url2 = 'https://basketball.realgm.com/ncaa/stats/2021/Averages/Qualified/All/Season/All/trb/desc/1/'
page2 = urlopen(url2)
soup2 = BeautifulSoup(page2,'html.parser')
table2 = soup2.find('table')

In [11]:
output_rows2 = []
for table_row in table2.findAll('tr'):
    columns2 = table_row.findAll('td')
    output_row2 = []
    for column2 in columns2:
        output_row2.append(column2.text)
    output_rows2.append(output_row2)
    
with open('RPGNCAA2021Stats.csv','w') as csvfile2:
    writer2 = csv.writer(csvfile2)
    writer2.writerows(output_rows2)

In [12]:
RPGNCAAstats = pd.read_csv('/Users/nickseah/IEE 577/Team Project/RPGNCAA2021Stats.csv',names = columns, index_col = '#' )
RPGNCAAstats.head()

,Player,Team,GP,MPG,FGM,FGA,FG%,3PM,3PA,3P%,...,FT%,TOV,PG,ORB,DRB,RPG,AGP,SPG,BPG,PPG
#,,,,,,,,,,,,,,,,,,,,,
1,Fardaws Aimaq,UVU,13,30.8,5.8,10.9,0.535,0.0,0.0,0.000,...,0.646,3.2,2.7,4.5,10.4,14.9,1.4,0.3,2.0,15.8
2,Jayveous McKinnis,JSU,10,33.2,5.0,8.7,0.575,0.0,0.0,0.000,...,0.769,2.7,3.0,3.8,9.3,13.1,0.4,1.2,2.1,13.0
3,Charles Bassey,WKU,16,29.4,7.1,12.1,0.591,0.6,1.9,0.290,...,0.738,2.5,2.5,3.4,8.8,12.2,0.8,0.2,3.4,17.8
4,Justin Champagnie,PITT,13,34.0,7.5,14.5,0.516,1.4,3.8,0.367,...,0.698,1.3,1.7,3.5,8.5,12.0,1.7,1.3,1.3,19.2
5,Norchad Omier,ASU,16,26.2,5.3,9.8,0.545,0.0,0.2,0.000,...,0.745,1.6,2.9,4.0,7.9,11.9,0.8,1.1,1.5,13.0

In [13]:
url3 = 'https://basketball.realgm.com/ncaa/stats/2021/Averages/Qualified/All/Season/All/blocks/desc/1/'
page3 = urlopen(url3)
soup3 = BeautifulSoup(page3,'html.parser')
table3 = soup3.find('table')

In [14]:
output_rows3 = []
for table_row in table3.findAll('tr'):
    columns3 = table_row.findAll('td')
    output_row3 = []
    for column3 in columns3:
        output_row3.append(column3.text)
    output_rows3.append(output_row3)
    
with open('BPGNCAA2021Stats.csv','w') as csvfile3:
    writer3 = csv.writer(csvfile3)
    writer3.writerows(output_rows3)

In [15]:
BPGNCAAstats = pd.read_csv('/Users/nickseah/IEE 577/Team Project/BPGNCAA2021Stats.csv',names = columns, index_col = '#' )
BPGNCAAstats.head()

,Player,Team,GP,MPG,FGM,FGA,FG%,3PM,3PA,3P%,...,FT%,TOV,PG,ORB,DRB,RPG,AGP,SPG,BPG,PPG
#,,,,,,,,,,,,,,,,,,,,,
1,K.C. Ndefo,SPC,15,27.7,4.7,9.6,0.486,0.1,0.7,0.091,...,0.548,2.5,3.2,1.5,4.5,6.1,1.5,1.4,4.1,12.1
2,Charles Bassey,WKU,16,29.4,7.1,12.1,0.591,0.6,1.9,0.290,...,0.738,2.5,2.5,3.4,8.8,12.2,0.8,0.2,3.4,17.8
3,Dajour Dickens,HU,16,25.1,2.7,4.7,0.573,0.0,0.0,0.000,...,0.641,1.4,3.5,1.7,4.8,6.4,0.4,0.5,3.3,6.9
4,Mouhamadou Gueye,SB,18,25.6,3.4,8.1,0.428,0.4,1.3,0.304,...,0.690,2.8,2.5,1.3,5.3,6.7,2.1,0.9,3.2,9.5
5,Michael Isler,PC,1,31.0,2.0,5.0,0.400,1.0,2.0,0.500,...,0.429,6.0,4.0,0.0,4.0,4.0,1.0,1.0,3.0,8.0

In [16]:
url4 = 'https://basketball.realgm.com/ncaa/stats/2021/Averages/Qualified/All/Season/All/steals/desc/1/'
page4 = urlopen(url4)
soup4 = BeautifulSoup(page4,'html.parser')
table4 = soup4.find('table')

In [17]:
output_rows4 = []
for table_row in table4.findAll('tr'):
    columns4 = table_row.findAll('td')
    output_row4 = []
    for column4 in columns4:
        output_row4.append(column4.text)
    output_rows4.append(output_row4)
    
with open('SPGNCAA2021Stats.csv','w') as csvfile4:
    writer4 = csv.writer(csvfile4)
    writer4.writerows(output_rows4)

In [18]:
SPGNCAAstats = pd.read_csv('/Users/nickseah/IEE 577/Team Project/SPGNCAA2021Stats.csv',names = columns, index_col = '#' )
SPGNCAAstats.head()

,Player,Team,GP,MPG,FGM,FGA,FG%,3PM,3PA,3P%,...,FT%,TOV,PG,ORB,DRB,RPG,AGP,SPG,BPG,PPG
#,,,,,,,,,,,,,,,,,,,,,
1,Jacob Gilyard,RICH,14,37.6,4.0,10.1,0.397,1.9,6.0,0.310,...,0.846,1.5,1.6,0.2,2.1,2.4,5.5,3.8,0.0,11.4
2,Devante' Jones,CCU,18,32.3,6.6,13.2,0.500,2.2,5.2,0.419,...,0.886,2.0,2.3,1.7,5.0,6.7,3.3,3.2,0.2,20.6
3,Jose Alvarado,GT,15,36.9,6.3,11.9,0.531,2.2,5.1,0.434,...,0.872,2.2,2.7,0.7,3.0,3.7,4.5,3.0,0.1,17.6
4,Traci Carter,UHA,17,30.9,3.7,9.8,0.380,1.4,3.6,0.377,...,0.744,2.3,2.9,0.3,2.7,3.0,3.4,2.9,0.2,10.5
5,Anthony Tarke,CSU,19,35.4,5.3,11.7,0.455,1.1,3.5,0.299,...,0.547,3.3,2.3,1.6,6.6,8.3,3.4,2.8,1.8,15.7